# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - 30hrhackathon-mruh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

        # Set up Node.js for building the React frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Zip both React build and PHP app for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./build ./public

      # Upload artifact to be used in deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-build
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16DB42F926EB4528AFB7A44243302452 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1BE8F7A9470548F18E754F6E89213350 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D511CC1718FA4BEEAE4474FBCD602766 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: '30hrhackathon-mruh'
          slot-name: 'Production'
          package: .
          
